
version: '3.8'

networks:
  fin-network:
    driver: bridge
    external: true


services:
  mongo:
    image: mongo:latest
    container_name: notifications-mongodb
    ports:
      - "${MONGO_PORT}:27017" # Expose MongoDB on port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME} # Set the root username
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD} # Set the root password
    volumes:
      - ./docker/mongo_data:/data/db
    networks:
      - fin-network


